# Generated by Django 5.1.1 on 2024-09-16 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_feelings_moodentry_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="MoodEntry",
        ),
    ]
